# Oh yeah!
language: node_js

# Node 18 binaries require glibc >= 2.28
dist: focal

# Add additional versions here as appropriate.
node_js:
  - 'stable'
  - '18'
  - '16'
  - '14'

# Lint errors should trigger a failure.
before_script: npm run lint

# Runs the coverage script (which runs the tests)
script: npm run cover

# Code coverage
after_success: npm run coveralls
